import type { Metadata } from "next";
import { inter, hankenGrotesk, geistSans, geistMono } from '@/app/fonts/font'
import "./globals.css";
import { cn } from "@/lib/utils";
import Navbar from "@/components/navbar";
import Footer from "@/components/footer";
import { Toaster } from "@/components/ui/sonner";
import { SessionProvider } from "next-auth/react";

export const metadata: Metadata = {
  title: "Dhwani",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={cn("min-h-screen flex flex-col bg-background font-hankenGrotesk antialiased",
          hankenGrotesk.variable,
          inter.variable,
          geistSans.variable,
          geistMono.variable
        )}
      >
        <SessionProvider>
        <div className="w-full relative">
          <Navbar />
          </div>
          <main className="min-h-screen flex flex-col justify-center items-center max-w-[1512px] w-full mx-auto px-8 py-20 out:px-0">
          {children}
          </main>
          <div className="bg-white w-full flex justify-center items-center">

          <Footer />
          </div>
          <Toaster />
          </SessionProvider>
      </body>
    </html>
  );
}
